### ISSUE TITLE
If including jQuery, then it can be used for selectors

### ISSUE THREAD

**Issue by tariqporter** [ckpantelides/weather#2]
https://github.com/ckpantelides/weather/blob/04fdcc62e00426e8ac4ce5c426307c8f9e6623d0/myscript.js#L152

You can use `jQuery click` event handler

https://api.jquery.com/click/

`document.getElementById('searchButton').onclick = function() {`

will become

`$('#searchButton').click(function() { ...`

**Comment by ckpanteli** [comment]
Yep this is definitely cleaner
